import React, { useEffect, useState } from 'react'
import Head from 'next/head'

import TopStoriesSection from '@/src/components/Home/topStorySection'
import SportSection from '@/src/components/Home/sportSection'
import NavBar from '@/src/components/navBar'
import { axiosApi } from '@/src/utils/axios'
import { newsApi } from '@/src/api'
import { usePreviousState } from '@/src/utils/usePreviousState'


export default function Home() {
  const [newsData, setNewsData] = useState()
  const [sportsData, setSportsData] = useState()
  const [order, setOrder] = useState('newest')
  const [loading, setLoading] = useState(true)
  const prevOrder = usePreviousState(order)
  useEffect(() => {
    fetchDataNewsSection()
    fetchDataSportsSection()
  }, [])

  useEffect(() => {
    if (prevOrder && prevOrder != order) {
      fetchDataNewsSection()
      fetchDataSportsSection()
    }
  }, [order])

  const fetchDataNewsSection = () => {
    axiosApi.get(newsApi({ section: 'news', order: order }))
      .then((res) => {
        setNewsData(res.data.response.results)
        setLoading(false)
      }).catch((err) => {
        setLoading(false)
        console.log(err)
      })
  }

  const fetchDataSportsSection = () => {

    axiosApi.get(newsApi({ section: 'sport|culture|lifeandstyle', order: order }))
      .then((res) => {
        setLoading(false)
        setSportsData(res.data.response.results)
      }).catch((err) => {
        setLoading(false)
        console.log(err)
      })
  }

  const getOrder = (e: string) => {
    setOrder(e)
  }

  if (loading) {
    return <main className="container loading" ><img src="/images/loading.svg" width={50} height={88} /></main>
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container'>
        <NavBar title="Top stories" getOrder={(e) => getOrder(e)} />
        {newsData && <TopStoriesSection data={newsData} />}
        {sportsData && <SportSection data={sportsData} />}
      </main>
    </>
  )
}



